Feature/boolean
jabardigitalservice/DataSae pull request #8
Opened 2023-09-27 07:32 UTC by agistyaanugrah

Add Feature boolean

2023-09-27 08:40 UTC, pipinfitriadi requested changes

2023-09-27 08:40 UTC, pipinfitriadi commented on tests/test_boolean.py
> +from . import MESSAGE
@agistyaanugrah 
```py
import random
import unittest

import pandas as pd

from . import MESSAGE
from datasae.boolean import Boolean, WarningDataDetailMessage
from datasae.utils import create_warning_data, WarningDataMessage
```

2023-09-27 08:42 UTC, pipinfitriadi commented on tests/test_boolean.py
> +from . import MESSAGE
Coverage Unittesting nya belum 100% @agistyaanugrah 

https://github.com/jabardigitalservice/DataSae/actions/runs/6323317661/job/17170807808?pr=8

Name                      Stmts   Miss  Cover   Missing
-------------------------------------------------------
datasae/__init__.py           0      0   100%
datasae/boolean.py           67      6    91%   52-53, 89, 131-132, 170
datasae/exception.py         28      0   100%
datasae/float.py            240      0   100%
datasae/integer.py          269      0   100%
datasae/utils.py             11      0   100%
tests/__init__.py             1      0   100%
tests/test_boolean.py        30      0   100%
tests/test_exception.py       7      0   100%
tests/test_float.py          71      0   100%
tests/test_integer.py       100      0   100%
-------------------------------------------------------
TOTAL                       824      6    99%

2023-09-27 08:44 UTC, pipinfitriadi requested changes
mohon bantuan fixingnya kakak @agistyaanugrah

2023-09-27 09:12 UTC, agistyaanugrah commented on tests/test_boolean.py
> +from . import MESSAGE
yang coverage pasti gaakan 100% dari functionya karna pasti ke cover sama function isinstance

2023-09-27 10:37 UTC, pipinfitriadi requested changes
sip tinggal coverage test nya ya @agistyaanugrah

2023-09-29 00:24 UTC, agistyaanugrah commented
initu kalau code nya kayak gini gaakan bisa 100 coverage nya karna udah ke filter di awal pake yg isintace boolean @adibintangprada

2023-09-29 02:58 UTC, adibintangprada commented
> initu kalau code nya kayak gini gaakan bisa 100 coverage nya karna udah ke filter di awal pake yg isintace boolean @adibintangprada

Berarti yg di staticmethod gaperlu pake isinstance? isinstancenya di yg basic function aja ya?

2023-09-29 06:57 UTC, pipinfitriadi approved these changes
well done @agistyaanugrah @adibintangprada

2023-09-29 06:57 UTC, merged